swiftlint_version: 0.40.1

opt_in_rules:
 - anyobject_protocol
 - array_init
 - attributes
 - closure_body_length
 - closure_end_indentation
 - closure_spacing
 - collection_alignment
 - conditional_returns_on_newline
 - contains_over_first_not_nil
 - convenience_type
 - discouraged_object_literal
 - discouraged_optional_boolean
 - discouraged_optional_collection
 - duplicate_imports
 - empty_count
 - empty_string
 - empty_xctest_method
 - fallthrough
 - fatal_error_message
 - file_header
 - first_where
 - force_unwrapping
 - identical_operands
 - implicit_return
 - implicitly_unwrapped_optional
 - joined_default_parameter
 - last_where
 - legacy_random
 - literal_expression_end_indentation
 - lower_acl_than_parent
 - modifier_order
 - multiline_arguments
 - multiline_arguments_brackets
 - multiline_function_chains
 - multiline_literal_brackets
 - multiline_parameters
 - multiline_parameters_brackets
 - nslocalizedstring_key
 - number_separator
 - object_literal
 - operator_usage_whitespace
 - overridden_super_call
 - override_in_extension
 - private_action
 - private_outlet
 - prohibited_super_call
 - redundant_nil_coalescing
 - sorted_first_last
 - sorted_imports
 - static_operator
 - strong_iboutlet
 - switch_case_on_newline
 - toggle_bool
 - trailing_closure
 - unavailable_function
 - unneeded_parentheses_in_closure_argument
 - unused_setter_value
 - vertical_parameter_alignment_on_call
 - vertical_whitespace_closing_braces
 - vertical_whitespace_opening_braces
 - weak_computed_property
 - xct_specific_matcher
 - yoda_condition

# Rules customization
conditional_returns_on_newline:
  if_only: true

file_header:
  required_pattern: |
                    \/\/
                    \/\/ StencilSwiftKit( UnitTests)?
                    \/\/ Copyright © 2019 SwiftGen
                    \/\/ MIT Licence
                    \/\/

line_length:
  warning: 120
  error: 200

nesting:
  type_level:
    warning: 2

# Exclude generated files
excluded:
  - XCTestManifests.swift
