swiftlint_version: 0.42.0

opt_in_rules:
 - anyobject_protocol
 - array_init
 - attributes
 - closure_body_length
 - closure_end_indentation
 - closure_spacing
 - collection_alignment
 - conditional_returns_on_newline
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_first_not_nil
 - contains_over_range_nil_comparison
 - convenience_type
 - discouraged_optional_boolean
 - discouraged_optional_collection
 - empty_collection_literal
 - empty_count
 - empty_string
 - empty_xctest_method
 - enum_case_associated_values_count
 - fallthrough
 - fatal_error_message
 - file_header
 - first_where
 - flatmap_over_map_reduce
 - force_unwrapping
 - identical_operands
 - implicit_return
 - implicitly_unwrapped_optional
 - indentation_width
 - joined_default_parameter
 - last_where
 - legacy_multiple
 - legacy_random
 - literal_expression_end_indentation
 - lower_acl_than_parent
 - modifier_order
 - multiline_arguments
 - multiline_arguments_brackets
 - multiline_function_chains
 - multiline_literal_brackets
 - multiline_parameters
 - multiline_parameters_brackets
 - nslocalizedstring_key
 - nslocalizedstring_require_bundle
 - number_separator
 - operator_usage_whitespace
 - optional_enum_case_matching
 - overridden_super_call
 - override_in_extension
 - prefer_self_type_over_type_of_self
 - prefer_zero_over_explicit_init
 - private_action
 - private_outlet
 - prohibited_super_call
 - raw_value_for_camel_cased_codable_enum
 - reduce_into
 - redundant_nil_coalescing
 - sorted_first_last
 - sorted_imports
 - static_operator
 - strong_iboutlet
 - switch_case_on_newline
 - toggle_bool
 - trailing_closure
 - unavailable_function
 - unneeded_parentheses_in_closure_argument
 - unowned_variable_capture
 - vertical_parameter_alignment_on_call
 - vertical_whitespace_closing_braces
 - vertical_whitespace_opening_braces
 - xct_specific_matcher
 - yoda_condition
 - test_case_accessibility
 - inclusive_language
 - unused_closure_parameter

# Rules customization
conditional_returns_on_newline:
  if_only: true

file_header:
  required_pattern: |
                    \/\/
                    \/\/ StencilSwiftKit( UnitTests)?
                    \/\/ Copyright © 2021 SwiftGen
                    \/\/ MIT Licence
                    \/\/

indentation_width:
  indentation_width: 2

line_length:
  warning: 120
  error: 200

nesting:
  type_level:
    warning: 2
