name: SwiftLint

on:
  push:
    branches: stable
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

env:
  xcode-version: 12.0.0

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Xcode Select
        uses: devbotsxyz/xcode-select@v1.0.0
        with:
          version: ${{ env.xcode-version }}
      - 
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      -
        name: Lint source code
        run: bundle exec rake lint:code
      -
        name: Lint tests source code
        run: bundle exec rake lint:tests
