name: Test Xcode

on:
  push:
    branches: stable
    paths:
      - '.github/workflows/test-xcode.yml'
      - '**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/test-xcode.yml'
      - '**/*.swift'

env:
  xcode-version: 12.0.0

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Xcode Select
        uses: devbotsxyz/xcode-select@v1.0.0
        with:
          version: ${{ env.xcode-version }}
      - 
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      -
        name: Run tests
        run: bundle exec rake xcode:test
